config/routes.rb
Rails.application.eager_load! if Rails.env.development?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Exchangepro::Application.routes.draw do
  get "payment_address" => "welcome#payment_address"
  get "payment_system" => "private/api_payment#index"
  post "create_api_payment" => "private/api_payment#create_api"
  unless Rails.env.production?
    resources :invite_friends, only: [:index]
    get "buy_coin" => "private/buy_coin#show"
    post "buy_coin/create" => "private/buy_coin#create"
    post "buy_coin/save_data" => "private/buy_coin#save_data"
  end

  get 'chatting' => 'chats#chatting'
  resources :chats
  get 'chat/:id' => 'chats#chat'
  scope :chatting do
    get "chats(.:format)" => "chats#index"
    get "chats/:id(.:format)" => "chats#show"
    get "chats/:id/messages(.:format)" => "chats#messages"
  end

  # get "/faqs" => 'faqs#index'
  # get '/faqs_create_account' => 'faqs#create_account'
  # get '/faqs_change_info_register' => 'faqs#change_info_register'
  # get '/faqs_pass_login' => 'faqs#about_pass_login'
  # get '/faqs_deposit_withdraw_coin' => 'faqs#deposit_withdraw_coin'
  # get '/faqs_trades' => 'faqs#trade'
  # get '/faqs_recived_send_coin' => 'faqs#recived_send_coin'
  # get '/faqs_about_ico' => 'faqs#about_ico'

  get "sendcoind/new"
  get '/about_us' => 'welcome#about'
  use_doorkeeper
  get "/contacts" => "contacts#new"
  resources "contacts", only: [:create]
  match 'admin/contacts_us/to_all_new', to: 'admin/contacts_us#to_all_new', via: 'get'
  match 'admin/contacts_us/to_all', to: 'admin/contacts_us#send_to_all', via: 'post'

  root 'welcome#index'
  # get '/term_of_use' => 'welcome#term_of_use'
  get '/company_about' => 'welcome#company_about'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/wait_activation' => 'sessions#wait_activation'
  get '/send_email_activation' => 'sessions#send_email_activation'
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  get 'success_message' => 'welcome#success_message'
  get 'about-us'=> 'welcome#about'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/confirm_password' => 'identities#confirm_password'
  # post '/verify_password' => 'identities#verify_password'
  post '/confirm_password' => 'identities#verify_password'
  get '/update_email' => 'identities#update_email'
  post '/update_email' => 'identities#change_email'

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]
  resources :accounts, only: :index

  namespace :verify do
    resource :sms_auth,    only: [:show, :update]
    resource :google_auth, only: [:show, :update, :edit, :destroy]
  end

  namespace :authentications do
    resources :emails, only: [:new, :create, :edit, :update]
    resources :identities, only: [:new, :create]
    resource :weibo_accounts, only: [:destroy]
  end

  get "/security" => "securities#edit"
  post "/security" => "securities#update"

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
    resources :activation_emails, only: [:edit]
  end

  resources :chats

  get '/chat/:id' => 'chats#chat'
  get '/get_chat_name' => 'chats#get_name'
  post '/update_chat_name' => 'chats#change_name'

  scope :groupchat do
    get "/chats(.:format)" => "chats#index"
    get "/chats/:id(.:format)" => "chats#show"
    get "/chats/:id/messages(.:format)" => "chats#messages"
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  get '/documents/oauth'
  resources :documents, only: [:show]
  resources :two_factors, only: [:show, :index, :update]
  resources :two_factors_access, only: [:index]
  post 'two_factors_access/verify', to: 'two_factors_access#verify'
  get "confirm_two_factor", to: "verify/google_auths#confirm_two_factor"
  post 'two_factor_verify', to: 'verify/google_auths#two_factor_verify'

  scope module: :private do
    get '/affiliates' => 'affiliates#index'
    unless Rails.env.production?
      post '/coin_trade/buy_create', to: 'coin_trades#buy_create'
      post '/coin_trade/sell_create', to: 'coin_trades#sell_create'
      get '/coin_trade/load_history', to: 'coin_trades#load_history'
      get 'download_xls_affiliate_proof' => "affiliates#download_xls_affiliate_proof"
    end

    resources :coin_trades, only: [:index]
    get '/id_document', to: 'id_documents#edit'
    # resource  :id_document, only: [:edit, :update]
    get '/bank_accounts/show', to: 'bank_accounts#show'
    put '/bank_accounts/edit', to: 'bank_accounts#update'
    patch '/bank_accounts/edit', to: 'bank_accounts#update'
    post '/bank_accounts/new', to: 'bank_accounts#create'
    resource :bank_accounts, only: [:edit, :new]

    resources :sendcoin, :only => [:create]
    get "/sendcoin" => 'sendcoin#new'
    get "/add_or_delete_email" => 'sendcoin#add_or_delete_email'
    get "/taocoin_exchange" => 'taocoin_exchange#new'
    get '/deposit_infomation' => 'deposit_infomations#new'
    resource :deposit_infomations, only: [:edit, :update, :create]


    resources :taocoin_exchange do
      collection do
        post 'create'
      end
    end
    resources :settings, only: [:index]

    patch '/api_tokens/:id/edit', to: 'api_tokens#update'
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :arbs, only: [:index, :update, :edit, :create]
    # get "arbs" => 'arbs#index'

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/sendcoin' => 'history#sendcoin', as: :sendcoin_history
    get '/history/receivecoin' => 'history#receivecoin', as: :receivecoin_history

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy] do
        collection do
          post :clear
        end
      end
      resources :order_bids, :only => [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, :only => [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'

    resources :tickets, only: [:index, :new, :create, :show] do
      member do
        patch :close
      end
      resources :comments, only: [:create]
    end
  end

  draw :admin

  mount APIv2::Mount => APIv2::Mount::PREFIX
  mount V1::Mount => V1::Mount::PREFIX
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  has_secure_password
  auth_key :email
  attr_accessor :old_password, :referrer_member_id

  MAX_LOGIN_ATTEMPTS = 5

  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, length: { minimum: 6, maximum: 64 }
  validates :password_confirmation, presence: true, length: { minimum: 6, maximum: 64 }

  before_validation :sanitize

  def increment_retry_count
    self.retry_count = (retry_count || 0) + 1
  end

  def too_many_failed_login_attempts
    retry_count.present? && retry_count >= MAX_LOGIN_ATTEMPTS
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  def self.valid_email?(email)
    email.present? &&(email =~ VALID_EMAIL_REGEX)
  end

  private

  def sanitize
    self.email.normalize_zen_han.try(:downcase!)
  end

end

app/controllers/authentications/identities_controller.rb
module Authentications
  class IdentitiesController < ApplicationController
    before_action :auth_member!, :login_with_social_network

    def new
      @identity = Identity.new(email: current_user.email)
    end

    def create
      identity = Identity.new(identity_params.merge(email: current_user.email))
      if identity.save && current_user.create_auth_for_identity(identity)
        redirect_to settings_path, notice: t('.success')
      else
        redirect_to new_authentications_identity_path, alert: identity.errors.full_messages.join(',')
      end
    end

    private

    def identity_params
      params.required(:identity).permit(:password, :password_confirmation)
    end

    def login_with_social_network
      redirect_to '/404.html' if !current_user.authentications.identity?
    end

  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  #before_filter :auth_anybody!, only: :new
  before_action :confirm_password, only: [:update_email]

  def new
    if current_user
      redirect_to accounts_path
      return
    end
    @identity = env['omniauth.identity'] || Identity.new
    @referrer_code = params[:code_referrer]
  end

  def edit
    @identity = current_user.identity
  end

  def update
    @identity = current_user.identity

    unless @identity.authenticate(params[:identity][:old_password])
      redirect_to edit_identity_path, alert: t('.auth-error') and return
    end

    if @identity.authenticate(params[:identity][:password])
      redirect_to edit_identity_path, alert: t('.auth-same') and return
    end

    if @identity.update_attributes(identity_params)
      current_user.send_password_changed_notification
      clear_all_sessions current_user.id
      reset_session
      redirect_to signin_path, notice: t('.notice')
    else
      render :edit
    end
  end

  def confirm_password
  end

  def verify_password
    @identity = current_user.identity
    result = @identity.authenticate(params[:identity][:password])
    if result
      redirect_to update_email_path
    else
      redirect_to :back, :alert => t('.password_not_correct')
    end
  end

  def update_email
  end

  def change_email
    params[:email] = params[:email].normalize_zen_han
    check_email_exits = Member.where(:email => params[:email]).exists?
    if check_email_exits
      redirect_to :back, alert: t('header.email_exit')
    else
      if !params[:email].nil? and Identity.valid_email?params[:email]
        token = current_user.send_mail_activation
        token.new_email = params[:email]
        token.save
        session[:active_mail] = token
        TokenMailer.edit_email(params[:email], token[:id]).deliver
        clear_all_sessions current_user.id
        reset_session
        redirect_to signin_path, :notice => t('header.send_mail')
      else
        redirect_to :back, :alert => t('header.error_email')
      end
    end
  end

  private
    def identity_params
      params.required(:identity).permit(:password, :password_confirmation)
    end
end

app/views/identities/confirm_password.html.erb
<%= render "shared/menu_settings" %>

<div id="submit_current_password_form">
  <h1 class="tilte-header"><%= t('header.password') %></h1>
	<%= simple_form_for :identity, :url => confirm_password_path, html: {class: "form-default"}, :method => :post do |f| %>
    <div class="form-group row">
      <div class="col-xs-12">
        <%= f.input :password, :label => false, :placeholder => '', hint: false %>
        <span class="hint"><%= t('header.password_note') %></span>
      </div>
    </div>

		<div class="form-group row button">
			<%= f.submit t('header.next'), :class => "btn button-primary"%>
		</div>

  <% end %>
</div>

app/views/identities/edit.html.erb
<%= render "shared/menu_settings" %>

<div id="change_passwod_form">
  <h1 class="tilte-header"><%= t('.reset_password') %></h1>
  <%= form_for @identity, html: {class: "form-default"} do |f| %>
    <div class="form-group">
      <%= f.label :old_password, t('.old_password'), class: "col-sm-4 col-xs-12 col-form-label" %>
      <div class="col-sm-7 col-xs-12">
        <%= f.text_field :old_password, type: :password, :label => false, :class => 'form-control', :placeholder => t('.old_password') %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "col-sm-4 col-xs-12 col-form-label" %>
      <div class="col-sm-7 col-xs-12">
        <%= f.text_field :password, type: :password, :label => false, :class => 'form-control', :placeholder => t('.new_password') %>
        <span class="hint"><%= t('.hint')%></span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: "col-sm-4 col-xs-12 col-form-label" %>
      <div class="col-sm-7 col-xs-12">
        <%= f.text_field :password_confirmation, type: :password, :label => false, :class => 'form-control', :placeholder => t('.confirm_password') %>
      </div>
    </div>

  	<div class="form-group text-center">
      <%= f.submit  t('.change'), :class => 'btn button-primary' %>
    </div>
  <% end %>
</div>

app/views/identities/new.html.erb
<div class="container">
  <div id="register_form" class="login_register_form">
    <h1 class="title-header"><%= t('header.signup') %></h1>
    <%= simple_form_for @identity, :url => '/auth/identity/register' do |f| %>
      <!-- <div class="form-group text-center register-button" id="signin_oauth">
        <div class="btn_facebook_twitter">
          <div class="col-sm-6 facebook">
            <%= link_to "/auth/facebook", :class => "btn-block btn-lg btn-social btn-facebook" do %>
              <span class="fa fa-facebook"></span><%= t("header.signup_facebook") %>
            <% end %>
          </div>
          <div class="col-sm-6 twitter">
            <%= link_to "/auth/twitter", :class => "btn-block btn-lg btn-social btn-twitter" do %>
              <span class="fa fa-twitter"></span><%= t("header.signup_twitter") %>
            <% end %>
          </div>
        </div>
      </div> -->
      <%= f.input :email, :input_html => {:name => 'email', :autofocus => 'true', :class => 'form-control'}, placeholder: t('simple_form.placeholders.session.email'), label: false %>
      <%= f.input :password, :input_html => {:name => 'password', :class => 'form-control'}, label: false, hint: false, placeholder: t('simple_form.placeholders.session.password'), :hint => t('.password_number') %>
      <%= f.input :password_confirmation, :input_html => {:name => 'password_confirmation'}, label: false, placeholder: t('activerecord.attributes.identity.password_confirmation') %>
      <%#=  f.input :referrer_member_id, :input_html => {:name => 'referrer_code', type: "number", style: "-webkit-appearance: none;", value: @referrer_code}, label: false, placeholder: t('activerecord.attributes.identity.referrer_code') %>
      <div class="form-group text-center term-link">
        <div class="term_content">
          <p><%= t('.check_term').html_safe%></p>
          <input id="check_term" name="check_term" type="checkbox" tabindex="5" value="Checked" class="check-first" onchange="document.getElementsByClassName('btn-sigup').disabled = !this.checked;">
        </div>
      </div>

      <div class="form-group text-center register-button">
        <%= f.button :submit, t('header.signup'), :class => 'button-primary btn-sigup',:disabled => 'true' %>
      </div>
      <% end %>
  </div>
</div>

app/views/identities/update_email.html.erb
<%= render "shared/menu_settings" %>

<div id="change_email_form">
  <h1 class="tilte-header"><%= t('header.email') %></h1>
	<h3 class="text-center note-2"><%= t('header.email_note') %></h3>
	<%= form_tag @identity, :url => update_email_path, :method => :post do %>
    <div class="form-group row">
      <div class="col-xs-12">
        <%= text_field_tag :email, "", class: 'form-control change-email-input', require: true %>
      </div>
    </div>

  	<div class="form-group text-center">
      <%= submit_tag t('header.update'), :class => 'button-primary' %>
    </div>
  <% end %>
</div>